- hosts: nodes[1]
  become: true
  vars:
    home_dir: '/root'
    client_info: '/root/client-info.yml'
    client_ip: 192.168.10.173
    username: sc
    password: vFVJ8Nrr
  tasks:
    - name: install Synology-CSI
      git:
        repo: 'https://github.com/SynologyOpenSource/synology-csi.git'
        dest: '/root/synology-csi'
        update: yes

    - name: update for microk8s
      replace:
        path: /root/synology-csi/deploy/kubernetes/v1.19/node.yml
        regexp: ': /var/lib/kubelet'
        replace: ': /var/snap/microk8s/common/var/lib/kubelet'

    - name: update of StorageClass
      replace:
        path: /root/synology-csi/deploy/kubernetes/v1.19/storage-class.yml
        regexp: '^reclaimPolicy: Retain'
        replace: 'reclaimPolicy: Delete'

    - name: create Secret file
      blockinfile:
        path: /root/client-info.yml
        create: yes
        block: |
          clients:
            - host: {{client_ip}}
              port: 5000
              https: false
              username: {{username}}
              password: {{password}}

