- hosts: nodes
  become: true
  tasks:
    - name: install Microk8s
      snap:
        name: microk8s
        classic: yes
        channel: 1.19/stable

    - name: start Microk8s
      command: microk8s start

    - name: enable iSCSI service
      service:
        name: iscsid
        state: started
        enabled: yes

- hosts: nodes[1:]
  vars:
    token_ttl: 300
  become: true
  serial: 1
  tasks:
    - name: get cluster-join command
      shell: microk8s add-node |sed - -n -e 2,2p
      #shell: microk8s add-node -l {{token_ttl}} |sed - -n -e 2,2p
      register: token_info
      delegate_to: "{{ groups['nodes'][0] }}"
      delegate_facts: true

    - set_fact:
        join_command: "{{ token_info.stdout }}"

    - debug:
        msg:
          token_info: "{{token_info.stdout}}"

    - name: add node
      shell: "{{ join_command }}"

- hosts: nodes[0]
  become: true
  vars:
    home_dir: '/root'
    client_info: '/root/client-info.yml'
    client_ip: 192.168.10.173
    username: sc
    password: vFVJ8Nrr
  tasks:
    - name: install Synology-CSI
      git:
        repo: 'https://github.com/SynologyOpenSource/synology-csi.git'
        dest: '/root/synology-csi'
        update: yes

    - name: update for microk8s
      replace:
        path: /root/synology-csi/deploy/kubernetes/v1.19/node.yml
        regexp: ': /var/lib/kubelet'
        replace: ': /var/snap/microk8s/common/var/lib/kubelet'

    - name: update of StorageClass
      replace:
        path: /root/synology-csi/deploy/kubernetes/v1.19/storage-class.yml
        regexp: '^reclaimPolicy: Retain'
        replace: 'reclaimPolicy: Delete'

    - name: create Secret file
      blockinfile:
        path: "{{client_info}}"
        create: yes
        block: |
          clients:
            - host: {{client_ip}}
              port: 5000
              https: false
              username: {{username}}
              password: {{password}}

    - command: microk8s kubectl create ns synology-csi
    - command: microk8s kubectl create secret -n synology-csi generic client-info-secret --from-file={{client_info}}
    - command: microk8s kubectl apply -f /root/synology-csi/deploy/kubernetes/v1.19/
