- name: make mount point
  file:
    path: "{{mount_point}}"
    state: directory

- name: mount target
  mount:
    name: "{{mount_point}}"
    src: "UUID={{iscsi[inventory_hostname].uuid}}"
    fstype: xfs
    opts: rw
    state: mounted
