- hosts: servers
  become: yes
  vars:
    apt_proxy: "{{groups['registry'][0]}}"
    apt_apps:
      - tmux
      - htop
      - qemu-guest-agent
  tasks:
    - import_tasks: 02_install_apps.yml

- hosts: servers
  vars:
    github_id: t0m0h1r0
  tasks:
    - name: import ssh-key
      shell: >
        ssh-import-id gh:{{github_id}}

- hosts: database
  become: yes
  vars:
    mount_point: /mnt/chia
  tasks:
    - file:
        path: "{{mount_point}}"
        state: directory
    - mount:
        name: "{{mount_point}}"
        src: /dev/sdb
        fstype: ext4
        opts: rw
        state: mounted

- hosts: iscsi
  become: yes
  vars:
    mount_point: /mnt/iscsi
    pv_name: chia_plots
    device: sdb
  tasks:
    - file:
        path: "{{mount_point}}"
        state: directory
    - mount:
        name: "{{mount_point}}"
        src: "/dev/{{device}}"
        fstype: xfs
        opts: ro
        state: mounted

