- hosts: registry
  become: yes
  vars:
    apt_apps:
      - docker.io
      - docker-compose
      - python3-docker
    snap_apps:
    pvs:
      - { "name": "docker_dir", "dir": "/var/lib/docker" }
  tasks:
    - import_tasks: 02_install_apps.yml
    - import_tasks: 06_config_docker.yml
    - import_tasks: 08_config_registry.yml

- hosts: servers
  become: yes
  vars:
    apt_proxy: "{{groups['registry'][0]}}"
    apt_apps:
      - docker.io
      - docker-compose
      - python3-docker
      - nfs-common
      - tmux
      - htop
  tasks:
    - import_tasks: 02_install_apps.yml
    - import_tasks: 06_config_docker.yml

- hosts: database
  become: yes
  vars:
    mount_point: /mnt/chia
    pv_name: chia_plots
    iscsi_list:
      - uuid: 946e6915-f235-4400-9c69-371992427bf9
    iscsi: "{{dict(ansible_play_batch|zip(iscsi_list))}}"
  tasks:
    - import_tasks: 11_config_mnt.yml

- hosts: iscsi
  become: yes
  vars:
    mount_point: /mnt/iscsi
    pv_name: chia_plots
  tasks:
    - file:
        path: "{{mount_point}}"
        state: directory
    - mount:
        name: "{{mount_point}}"
        src: /dev/sdb1
        fstype: xfs
        opts: ro
        state: mounted
    - community.docker.docker_volume:
        name: "{{item.name}}"
        driver_options:
          type: none
          o: bind
          device: "{{item.dir}}"
      loop:
          - { "name": "{{pv_name}}", "dir": "{{mount_point}}/chia/plots" }

- hosts: nas
  become: yes
  vars:
    nas:
      qnap:
        dir: /share/chia/plots/
      omv:
        dir: /srv/mergerfs/x/chia/plots/
    pv_name: chia_plots
    drive: "{{nas[hostvars[inventory_hostname].vendor]}}"
  tasks:
    - import_tasks: 15_config_nas.yml

- hosts: workers managers
  become: yes
  vars:
    labels:
      managers:
        ldap: "true"
      iscsi:
        storage: "true"
      nas:
        storage: "true"
      compute:
        compute: "true"
      database:
        database: "true"
        grafana: "true"
  tasks:
    - import_tasks: 07_config_swarm.yml

