- hosts: registry
  become: yes
  vars:
    apt_apps:
      - docker.io
      - docker-compose
      - python3-docker
    snap_apps:
    pvs:
      - { "name": "docker_dir", "dir": "/var/lib/docker" }
  tasks:
    - import_tasks: 02_install_apps.yml
    - import_tasks: 06_config_docker.yml
    - import_tasks: 08_config_registry.yml

- hosts: servers
  become: yes
  vars:
    apt_proxy: "{{groups['registry'][0]}}"
    apt_apps:
      - docker.io
      - docker-compose
      - python3-docker
      - nfs-common
      - tmux
      - htop
  tasks:
    - import_tasks: 02_install_apps.yml
    - import_tasks: 06_config_docker.yml

- hosts: managers
  become: yes
  vars:
    mount_point: /mnt/chia
    pv_name: chia_plots
    iscsi_list:
      - uuid: 50d74254-1324-4711-9e66-77be854a3de1
    iscsi: "{{dict(ansible_play_batch|zip(iscsi_list))}}"
  tasks:
    - import_tasks: 11_config_mnt.yml

- hosts: iscsi
  become: yes
  vars:
    mount_point: /mnt/iscsi
    pv_name: chia_plots
    iscsi_list:
      - portal: syn2
        target: iqn.2000-01.com.synology:syn2.Target-1.4007cab6d73
        uuid: 5ef36ece-6516-4100-b92d-089e66cb9ad9
      - portal: syn2
        target: iqn.2000-01.com.synology:syn2.Target-2.4007cab6d73
        uuid: c832e454-b781-45c8-aaf9-4ee090f9f0b8
      - portal: qnap2
        target: iqn.2004-04.com.qnap:ts-832px:iscsi.target.576194
        uuid: ef1db905-7000-4265-bbd7-7b2bfdc3f976
      - portal: qnap1
        target: iqn.2004-04.com.qnap:ts-832x:iscsi.target1.506276
        uuid: 5ec26b4d-882f-4acf-9c4c-04a0ca7db285
#      - portal: syn1
#        target: iqn.2000-01.com.synology:syn1.Target-1.9c3409d65fa
#        uuid: 51c5c903-3052-4b42-a238-a101e8e729d1
    iscsi: "{{dict(ansible_play_batch|zip(iscsi_list))}}"
    #iscsi: "{{dict(ansible_play_batch|zip_longest(iscsi_list,fillvalue=iscsi_list[0]))}}"
  tasks:
    - import_tasks: 05_config_iscsi.yml

- hosts: nas
  become: yes
  vars:
    nas:
      qnap:
        dir: /share/chia/plots/
      omv:
        dir: /srv/mergerfs/x/chia/plots/
    pv_name: chia_plots
    drive: "{{nas[hostvars[inventory_hostname].vendor]}}"
  tasks:
    - import_tasks: 15_config_nas.yml

- hosts: workers managers
  become: yes
  vars:
    labels:
      managers:
        ldap: "true"
      iscsi:
        storage: "true"
      nas:
        storage: "true"
      compute:
        compute: "true"
      database:
        database: "true"
        grafana: "true"
  tasks:
    - import_tasks: 07_config_swarm.yml

