- hosts: workers
  become: true
  tasks:
    - name: install librarries
      apt:
        name: "{{item}}"
        update_cache: yes
        cache_valid_time: 86400 #One day
      loop:
        - docker.io
        - docker-compose
        - python3-docker

- hosts: workers
  become: true
  tasks:
    - set_fact:
        docker_vars: {}
    - name: append key/values
      set_fact:
        docker_vars: "{{ docker_vars | default([]) | combine({ item.key : item.value }) }}"
      loop:
        - { key: "insecure-registries", value: [ "{{inventory_hostname}}:5000" ] }
    - name: write var to file
      copy:
        content: "{{ docker_vars | to_nice_json }}"
        dest: /etc/docker/daemon.json
      notify:
        - restart Docker

  handlers:
    - name: restart Docker
      service:
        name: docker
        state: restarted
        enabled: yes

- hosts: workers
  become: true
  tasks:
    - name: start Docker registry
      community.docker.docker_container:
        name: registry
        image: registry:latest
        ports:
          - 5000:5000
        state: started
