- name: create /etc/docker/daemon.json
  template:
    src: "06_daemon.json.j2"
    dest: "/etc/docker/daemon.json"
  notify:
    - restart Docker

- name: create PVs 
  community.docker.docker_volume:
    name: "{{item.name}}"
    driver_options:
      type: none
      o: bind
      device: "{{item.dir}}"
  loop: "{{pvs}}"

- name: join worker nodes
  community.docker.docker_swarm:
    remote_addrs: "{{groups['managers'][0]}}"
    join_token: "{{tokens.manager}}"
    state: join
  when: 
    - inventory_hostname != groups['managers'][0]
    - inventory_hostname in groups['managers']

- name: join worker nodes
  community.docker.docker_swarm:
    remote_addrs: "{{groups['managers'][0]}}"
    join_token: "{{tokens.worker}}"
    state: join
  when: 
    - inventory_hostname in groups['workers']
