- name: create /etc/docker/daemon.json
  file:
    path: /etc/docker
    state: directory
- template:
    src: "06_daemon.json.j2"
    dest: "/etc/docker/daemon.json"

- name: restart Docker daemon
  service:
    name: docker
    state: restarted
    enabled: yes


- name: create PVs 
  community.docker.docker_volume:
    name: "{{item.name}}"
    driver_options:
      type: none
      o: bind
      device: "{{item.dir}}"
  loop: "{{pvs}}"

