- name: start Docker registry
  community.docker.docker_container:
    name: registry
    image: registry:latest
    ports:
      - 5000:5000
    state: started
    restart_policy: always
- name: start apt proxy
  community.docker.docker_container:
    name: apt-cacher
    image: sameersbn/apt-cacher-ng:latest
    ports:
      - 3142:3142
    state: started
    restart_policy: always


