# QNAPの場合
#   Qnap Clubのリポジトリ(https://www.qnapclub.eu/en/repo.xml)をApp Centerに登録
#   Entware-stdをインストール
#   sshでログイン
#   python3をインストール(opkg install pythoon3 python3-pip)
#   dockerライブラリをインストール(pip install docker)

- debug: msg="{{drive}}"
- name: create PVs 
  community.docker.docker_volume:
    name: "{{item.name}}"
    driver_options:
      type: none
      o: bind
      device: "{{item.dir}}"
  loop:
      - { "name": "{{pv_name}}", "dir": "{{drive.dir}}" }
