- hosts: nas
  #become: yes
  vars:
    nas:
      qnap:
        dir: /share/chia/plots/
      omv:
        dir: /srv/mergerfs/x/chia/plots/
    pv_name: test
    drive: "{{nas[hostvars[inventory_hostname].vendor]}}"
  tasks:
    - import_tasks: 15_config_nas.yml
