- hosts: servers
  become: yes
  vars:
    nic: "{{hostvars[inventory_hostname].nic}}"
    mac_top: fe:ff:00:00:00:00
    mac_sub: 00:00:ff:ff:ff:ff
    mac: "{{ ((mac_top|hwaddr('int'))+(mac_sub|hwaddr('int')|random(seed=inventory_hostname)))|hwaddr('linux') }}"
  tasks:
    - debug:
        msg: "{{mac}}"
