- hosts: workers
  become: yes
  vars:
    apt_proxy: "{{groups['registry'][0]}}"
    apt_apps:
      - docker.io
      - docker-compose
      - python3-docker
      - ansible
      - open-iscsi
    snap_apps:
    pvs:
      - { "name": "chia_plots", "dir": "{{mount_point}}/chia/plots" }
      - { "name": "docker_dir", "dir": "/var/lib/docker" }
    mount_point: /mnt/iscsi
    iscsi_list:
      - portal: syn1
        target: iqn.2000-01.com.synology:syn1.Target-1.9c3409d65fa
        uuid: 5ef36ece-6516-4100-b92d-089e66cb9ad9
      - portal: syn1
        target: iqn.2000-01.com.synology:syn1.Target-1.9c3409d65fa
        uuid: 5ef36ece-6516-4100-b92d-089e66cb9ad9
    iscsi: "{{dict(ansible_play_batch|zip(iscsi_list))}}"
  tasks:
    - debug: msg="{{iscsi[inventory_hostname]}}"
