- hosts: servers
  become: yes
  vars:
    nic: "{{hostvars[inventory_hostname].nic}}"
  tasks:
    - import_tasks: 01_config_network.yml
  handlers:
    - import_tasks: 01_apply_config.yml

- hosts: servers[0]
  tasks:
    - import_tasks: 09_deploy_vms.yml 
      when: inventory_hostname == groups['servers'][0]

- hosts: registry
  become: yes
  vars:
    apt_apps:
      - docker.io
      - docker-compose
      - python3-docker
    snap_apps:
    pvs:
      - { "name": "docker_dir", "dir": "/var/lib/docker" }
  tasks:
    - import_tasks: 02_install_apps.yml
    - import_tasks: 06_config_docker.yml
    - import_tasks: 08_config_registry.yml

- hosts: workers managers
  become: yes
  vars:
    apt_proxy: "{{groups['registry'][0]}}"
    apt_apps:
      - docker.io
      - docker-compose
      - python3-docker
      - ansible
      - open-iscsi
    snap_apps:
    pvs:
      - { "name": "chia_plots", "dir": "{{mount_point}}/chia/plots" }
      - { "name": "docker_dir", "dir": "/var/lib/docker" }
    iscsi_target: "{{groups['iscsi'][0]}}"
    iscsi_iqn: iqn.2000-01.com.synology:syn1.Target-1.9c3409d65fa
    iscsi_uuid: 5ef36ece-6516-4100-b92d-089e66cb9ad9
    mount_point: /mnt/iscsi
  tasks:
    - import_tasks: 02_install_apps.yml
    - import_tasks: 05_config_iscsi.yml
    - import_tasks: 06_config_docker.yml
    - import_tasks: 07_config_swarm.yml
