- hosts: nucs
  vars:
    eth_dev: eno1
  tasks:
    - import_tasks: 01_config_network.yml
    - import_tasks: 09_deplooy_vms.yml 
      when: inventory_hostname == groups['nucs'][0]
  handlers:
    - import_tasks: 01_apply_config.yml

- hosts: registry
  become: yes
  vars:
    apt_apps:
      - docker.io
      - docker-compose
      - python3-docker
    snap_apps:
  tasks:
    - import_tasks: 02_install_apps.yml
    - import_tasks: 06_config_docker.yml
    - import_tasks: 08_config_registry.yml
