- hosts: workers
  vars:
  become: true
  tasks:
    - name: install librarries
      apt:
        name: "{{item}}"
        update_cache: yes
        cache_valid_time: 86400 #One day
      loop:
        - docker.io
        - docker-compose
        - python3-docker

    - set_fact:
        docker_vars: {}
    - set_fact:
        docker_vars: "{{ docker_vars | default([]) | combine({ item.key : item.value }) }}"
      loop:
        - { key: "insecure-registries", value: [ "{{groups['registry'][0]}}:5000" ] }
    - name: write var to file
      copy:
        content: "{{ docker_vars | to_nice_json }}"
        dest: /etc/docker/daemon.json
      notify: restart Docker

  handlers:
    - name: restart Docker
      service:
        name: docker
        state: restarted
        enabled: yes


- hosts: workers
  vars:
    iscsi_target: 192.168.10.173
    iscsi_iqn: iqn.2000-01.com.synology:syn1.default-target.9c3409d65fa
    iscsi_uuid: 511bfdf5-99f7-45d3-83aa-1a31ecbfd844
    mount_point: /mnt/iscsi
  become: true
  tasks:
    - name: restart iSCSI
      service:
        name: iscsid
        state: started
        enabled: yes

    - name: login iSCSI target
      community.general.open_iscsi:
        portal: "{{iscsi_target}}"
        target: "{{iscsi_iqn}}"
        #discover: yes
        login: yes
        auto_node_startup: true

    - name: make mount point
      file:
        path: "{{mount_point}}"
        state: directory

    - name: mount iSCSI target
      mount:
        name: "{{mount_point}}"
        src: "UUID={{iscsi_uuid}}"
        fstype: xfs,ro
        opts: _netdev
        state: mounted

- hosts: workers
  vars:
    mount_point: /mnt/iscsi
    docker_token: SWMTKN-1-39rudkfcvqnt8nnw8qnrvzt9u6uljeh13zw5fs0ye3ovp09tjy-574y8bblenotd3il7v6wca5f4
  become: true
  tasks:
    - name: create PV for plots
      community.docker.docker_volume:
        name: "{{item.name}}"
        driver_options:
          type: none
          o: bind
          device: "{{item.dir}}"
      loop:
        - { "name": "chia_plots", "dir": "{{mount_point}}/chia/plots" }
        - { "name": "docker_dir", "dir": "/var/lib/docker" }

    - name: join Docker swarm
      community.docker.docker_swarm:
        remote_addrs: "{{groups['masters']}}"
        join_token: "{{docker_token}}"
        state: join
      notify:
        - set node labels

  handlers:
    - name: set node labels
      pause:
        seconds: 10
    - delegate_to: "{{groups['masters'][0]}}"
      community.docker.docker_node:
        hostname: "{{inventory_hostname}}"
        labels:
          storage: "true"
        labels_state: replace
