- hosts: masters
  vars:
  tasks:
    - name: install librarries
      snap:
        name: "{{item}}"
      loop:
        - lxd

    - name: create profile
      community.general.lxd_profile:
        name: bridge
        state: present
        config: {}
        devices:
          eth0:
            nictype: bridged
            parent: br0
            type: nic
          root:
            path: /
            pool: default
            type: disk
    - name: deploy VMs
      community.general.lxd_container:
#        name: "{{item}}"
        name: test
        type: virtual-machine
        state: started
#        source:
#          type: image
#          mode: pull
#          server: https://images.linuxcontainers.org
#          alias: ubuntu/focal/amd64
#        profiles: ["bridge"]
#        config:
#          limits.cpu: "1"
#          limits.memory: 1GiB
#        wait_for_ipv4_addresses: true
#      loop: "{{groups['vms']}}"

